/**
 * Stage 12 — Compile decidable rule detectors to tools/lint/design-rules.mjs.
 *
 * Reads:  cache/_corpus/emitted-rules.json
 * Writes: tools/lint/design-rules.mjs
 *         tools/lint/lint-misfires.md
 *
 * Only rules with decidable ∈ {'full', 'partial'} and detector.kind ≠ 'none'
 * are compiled.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CACHE_DIR = resolve(__dirname, 'cache');
const CORPUS_DIR = resolve(CACHE_DIR, '_corpus');
const EMITTED_PATH = resolve(CORPUS_DIR, 'emitted-rules.json');
const LINT_DIR = resolve(__dirname, '../../tools/lint');
const OUT_LINTER = resolve(LINT_DIR, 'design-rules.mjs');
const MISFIRES_PATH = resolve(LINT_DIR, 'lint-misfires.md');

const args = process.argv.slice(2);
const FORCE = args.includes('--force');

function generateCheckFn(rule) {
  const { id, modality, statement, detector } = rule;
  const kind = detector?.kind;

  if (!kind || kind === 'none' || kind === 'ast') return null;

  const excludePaths = detector.exclude_paths ?? [
    'node_modules/**', 'dist/**', '.vite/**', 'cache/**',
  ];
  const pattern = detector.pattern;
  const cssOnly = kind === 'css-prop';
  const fileFilter = cssOnly ? `f.endsWith('.css')` : `true`;
  const escapedId = JSON.stringify(id);
  const escapedStatement = JSON.stringify(statement);
  const escapedModality = JSON.stringify(modality);
  const escapedExcludes = JSON.stringify(excludePaths);

  return `
// Rule: ${id} [${modality}]
// ${statement}
async function check_${id.replace(/[^a-zA-Z0-9_]/g, '_')}(rootDir) {
  const re = new RegExp(${JSON.stringify(pattern)}, 'g');
  const excludes = ${escapedExcludes};
  const violations = [];
  const files = await getAllFiles(rootDir, f => ${fileFilter} && !isExcluded(f, excludes, rootDir));
  for (const file of files) {
    let text;
    try { text = await readFile(file, 'utf8'); } catch { continue; }
    let m;
    while ((m = re.exec(text)) !== null) {
      const lineNum = text.slice(0, m.index).split(String.fromCharCode(10)).length;
      violations.push({
        ruleId: ${escapedId},
        modality: ${escapedModality},
        statement: ${escapedStatement},
        file,
        line: lineNum,
        match: m[0],
      });
    }
  }
  return violations;
}`;
}

function generateLinterModule(decidableRules, astSkipped) {
  const checkFns = decidableRules.map(generateCheckFn).filter(Boolean);
  const fnNames = decidableRules
    .filter(rule => rule.detector?.kind && rule.detector.kind !== 'none' && rule.detector.kind !== 'ast')
    .map(rule => `check_${rule.id.replace(/[^a-zA-Z0-9_]/g, '_')}`);
  const newline = String.fromCharCode(10);
  const checksSource = fnNames.length
    ? newline + '  ' + fnNames.join(',' + newline + '  ') + newline
    : '';
  const astNote = astSkipped.length
    ? `// AST detectors not yet implemented — skipped rules: ${astSkipped.join(', ')}${newline}`
    : '';

  return `/**
 * Design-rule linter — generated by tools/scrape/lint-compile.mjs
 * DO NOT EDIT — re-generate via npm run scrape:lint-compile
 */
/* eslint-disable */

import { readFile, readdir } from 'node:fs/promises';
import { resolve, relative, basename } from 'node:path';
import { minimatch } from 'minimatch';

${astNote}
async function getAllFiles(dir, filter) {
  const results = [];
  async function walk(d) {
    let entries;
    try { entries = await readdir(d, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
      const full = resolve(d, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
      } else if (entry.isFile() && filter(full)) {
        results.push(full);
      }
    }
  }
  await walk(dir);
  return results;
}

function isExcluded(file, patterns, rootDir) {
  const rel = relative(rootDir, file);
  return patterns.some(pattern => {
    try { return minimatch(rel, pattern, { dot: true }); } catch { return false; }
  });
}

${checkFns.join(String.fromCharCode(10))}

const CHECKS = [${checksSource}];

export async function runAll(rootDir) {
  const all = [];
  for (const check of CHECKS) {
    const violations = await check(rootDir);
    all.push(...violations);
  }
  return all;
}

if (basename(process.argv[1] ?? '') === 'design-rules.mjs') {
  const root = process.argv[2] || resolve(new URL(import.meta.url).pathname, '../../../assets');
  const violations = await runAll(root);
  if (violations.length === 0) {
    process.stdout.write('design-rules: no violations.' + String.fromCharCode(10));
    process.exit(0);
  }
  for (const violation of violations) {
    process.stdout.write(
      `[VIOLATION] ${violation.ruleId} [${violation.modality}] ${violation.file}:${violation.line} — ${violation.statement}` +
      String.fromCharCode(10)
    );
  }
  process.stdout.write(`${violations.length} violation(s) found.` + String.fromCharCode(10));
  process.exit(1);
}
`;
}

const MISFIRES_HEADER = `# Lint Misfires Log

Append-only. When a detector triggers on valid code, log it here, triage the rule,
and demote to \`decidable: 'judgment'\` if the false-positive rate is too high.

| Date | Rule ID | File | Context | Action |
| --- | --- | --- | --- | --- |
`;

async function main() {
  if (!existsSync(EMITTED_PATH)) {
    console.error('Missing emitted-rules.json — run scrape:emit first.');
    process.exit(1);
  }
  if (!FORCE && existsSync(OUT_LINTER)) {
    process.stdout.write(`Exists: ${OUT_LINTER} (use --force)` + String.fromCharCode(10));
    process.exit(0);
  }

  const raw = JSON.parse(await readFile(EMITTED_PATH, 'utf8'));
  const allRules = raw.rules ?? [];
  const decidable = allRules.filter(
    rule => rule.decidable !== 'judgment' && rule.detector?.kind && rule.detector.kind !== 'none',
  );
  const astSkipped = decidable.filter(rule => rule.detector?.kind === 'ast').map(rule => rule.id);
  const compilable = decidable.filter(rule => rule.detector?.kind !== 'ast');

  process.stdout.write(`Total rules: ${allRules.length}` + String.fromCharCode(10));
  process.stdout.write(`Decidable (non-judgment): ${decidable.length}` + String.fromCharCode(10));
  process.stdout.write(`Compilable (regex/css-prop): ${compilable.length}` + String.fromCharCode(10));
  if (astSkipped.length) {
    process.stdout.write(`AST skipped (not yet implemented): ${astSkipped.length}` + String.fromCharCode(10));
  }

  await mkdir(LINT_DIR, { recursive: true });
  await writeFile(OUT_LINTER, generateLinterModule(decidable, astSkipped), 'utf8');
  process.stdout.write(`Wrote ${OUT_LINTER}` + String.fromCharCode(10));

  if (!existsSync(MISFIRES_PATH)) {
    await writeFile(MISFIRES_PATH, MISFIRES_HEADER, 'utf8');
    process.stdout.write(`Created ${MISFIRES_PATH}` + String.fromCharCode(10));
  }

  if (compilable.length === 0) {
    process.stdout.write(
      'No compilable detectors yet — linter is a no-op until decidable rules are hand-authored.' +
      String.fromCharCode(10)
    );
  }
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
