/**
 * Manual-paste queue (plan.md section 4a) — shared by fetch.mjs and clean.mjs.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..', '..');
export const QUEUE_PATH = resolve(ROOT, 'blog/ideas/create rules for ai/manual-paste.queue.md');

const QUEUE_HEADER = `# Manual Paste Queue\n\nGenerated by tools/scrape pipeline. Append-only.\nRun \`npm run scrape:paste\` to process pending entries.\n\n---\n\n`;

export function loadQueueEntries() {
  if (!existsSync(QUEUE_PATH)) return [];
  const raw = readFileSync(QUEUE_PATH, 'utf8');
  const entries = [];
  const entryRegex = /^- id: (.+)\n  url: (.+)\n  status: (.+)\n  reason: (.+)\n  detected_at: (.+)\n  source_index: (.+)$/gm;
  let m;
  while ((m = entryRegex.exec(raw)) !== null) {
    entries.push({
      id: m[1].trim(),
      url: m[2].trim(),
      status: m[3].trim(),
      reason: m[4].trim(),
      detected_at: m[5].trim(),
      source_index: m[6].trim(),
    });
  }
  return entries;
}

export function appendQueueEntry(entry) {
  const line = [
    `- id: ${entry.id}`,
    `  url: ${entry.url}`,
    `  status: ${entry.status}`,
    `  reason: ${entry.reason}`,
    `  detected_at: ${entry.detected_at}`,
    `  source_index: ${entry.source_index}`,
  ].join('\n') + '\n';

  if (!existsSync(QUEUE_PATH)) {
    mkdirSync(dirname(QUEUE_PATH), { recursive: true });
    writeFileSync(QUEUE_PATH, QUEUE_HEADER + line, 'utf8');
  } else {
    const existing = readFileSync(QUEUE_PATH, 'utf8');
    writeFileSync(QUEUE_PATH, existing + '\n' + line, 'utf8');
  }
}

export function queueIdsSet() {
  return new Set(loadQueueEntries().map(e => e.id));
}
