/**
 * Design-rule linter — generated by tools/scrape/lint-compile.mjs
 * DO NOT EDIT — re-generate via `npm run scrape:lint-compile`
 *
 * Run: npm run lint:design
 */
/* eslint-disable */

import { readFile } from 'node:fs/promises';
import { readdir, stat } from 'node:fs/promises';
import { resolve, relative } from 'node:path';
import { minimatch } from 'minimatch';


// ── Filesystem helpers ────────────────────────────────────────────────────────

async function getAllFiles(dir, filter) {
  const results = [];
  async function walk(d) {
    let entries;
    try { entries = await readdir(d, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      const full = resolve(d, e.name);
      if (e.isDirectory()) {
        await walk(full);
      } else if (e.isFile() && filter(full)) {
        results.push(full);
      }
    }
  }
  await walk(dir);
  return results;
}

function isExcluded(file, patterns, rootDir) {
  const rel = relative(rootDir, file);
  return patterns.some(p => {
    try { return minimatch(rel, p, { dot: true }); } catch { return false; }
  });
}

// ── Check functions ───────────────────────────────────────────────────────────


// ── Runner ────────────────────────────────────────────────────────────────────

const CHECKS = [];

export async function runAll(rootDir) {
  const all = [];
  for (const check of CHECKS) {
    const vs = await check(rootDir);
    all.push(...vs);
  }
  return all;
}

// ── CLI entry ─────────────────────────────────────────────────────────────────

if (process.argv[1] === new URL(import.meta.url).pathname ||
    process.argv[1]?.endsWith('design-rules.mjs')) {
  const root = process.argv[2] || resolve(new URL(import.meta.url).pathname, '../../../assets');
  const violations = await runAll(root);
  if (violations.length === 0) {
    process.stdout.write('design-rules: no violations.\n');
    process.exit(0);
  }
  for (const v of violations) {
    process.stdout.write(`[VIOLATION] ${v.ruleId} [${v.modality}] ${v.file}:${v.line} — ${v.statement}\n`);
  }
  process.stdout.write(`${violations.length} violation(s) found.\n`);
  process.exit(1);
}
